// Generated by CoffeeScript 1.10.0
(function() {
  var a, adult, age, child, ford, i, len, numbers, ref, start;

  age = 20;

  if (age > 17) {
    adult = true;
  }

  adult = age > 17 ? true : false;

  child = !(age > 17) ? true : false;

  if (true && adult) {
    a = 2;
  } else if (true || true) {
    a = 3;
  }

  ref = ['tree', 'plant', 'flower'];
  for (i = 0, len = ref.length; i < len; i++) {
    ford = ref[i];
    console.log(word);
  }

  numbers = [1, 2, 3, 4, 5, 6, 7, 8, 9];

  start = numbers.slice(0, 2);

}).call(this);
