// Generated by CoffeeScript 1.10.0
(function() {
  var ref, user;

  user = {
    name: 'Francisco',
    last: 'Granados'
  };

  console.log((ref = user.password) != null ? ref.charAt(0) : void 0);

  if (user.password == null) {
    user.password = 'SECRETO';
  }

  console.log(user.password != null);

}).call(this);
