// Generated by CoffeeScript 1.10.0
(function() {
  var adult, age, child, op, result;

  op = '?';

  result = (function() {
    switch (op) {
      case '+':
        return 5 + 4;
      case '-':
        return 5 - 4;
      default:
        return 54;
    }
  })();

  console.log(op, result);

  age = 20;

  adult = age > 17 ? true : false;

  console.log(age, adult);

  age = 8;

  child = (2 < age && age < 12);

  console.log("child: " + child);

}).call(this);
