// Generated by CoffeeScript 1.10.0
(function() {
  var aParam, emptyParams, fatFunc, mParam, oneParam, saludar,
    slice = [].slice;

  emptyParams = function() {};

  oneParam = function(param) {
    return console.log(param);
  };

  aParam = function(param, msg) {
    if (msg == null) {
      msg = "hola";
    }
    return console.log(msg);
  };

  mParam = function() {
    var one, others, two;
    one = arguments[0], two = arguments[1], others = 3 <= arguments.length ? slice.call(arguments, 2) : [];
    return console.log(others);
  };

  this["var"] = 1;

  fatFunc = (function(_this) {
    return function() {
      return _this["var"];
    };
  })(this);

  saludar = function() {
    return console.log('Hola');
  };

  $('button').click(saludar);

}).call(this);
