// Generated by CoffeeScript 1.10.0
(function() {
  $(document).ready(function() {
    var onclick;
    console.log('ready');
    onclick = function() {
      return console.log('clic');
    };
    return $('button').click(onclick);
  });

}).call(this);
