// Generated by CoffeeScript 1.10.0
(function() {
  var edad, myFunction, name, ref, trace, user, var1, var2;

  myFunction = function() {
    return console.log('myFunction');
  };

  myFunction();

  trace = function(msg) {
    return console.log(msg);
  };

  name = 'Sebastian';

  edad = 19;

  user = {
    name: 'carlos',
    age: 40,
    friend: {
      name: 'Liz',
      age: 17
    }
  };

  trace(user);

  ref = ['valor1', 'valor2'], var1 = ref[0], var2 = ref[1];

}).call(this);
